# Generated by Django 4.2.4 on 2023-09-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(default='Add bio', null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='streetaddress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jobField',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobfield'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jobTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
