# Generated by Django 4.2.4 on 2023-08-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='jobField',
            new_name='jobField_id',
        ),
    ]
