# Generated by Django 4.2.4 on 2023-08-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_jobfield_userinfo_jobfield_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='jobField_id',
            new_name='jobField',
        ),
    ]
