# Generated by Django 4.2.4 on 2023-08-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_jobfield_id_userinfo_jobfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='jobField',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='jobTitle',
        ),
    ]
