# Generated by Django 4.2.4 on 2023-08-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_google',
        ),
    ]
