# Generated by Django 4.2.4 on 2023-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_is_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('company', 'company'), ('admin', 'admin')], default='user', max_length=30),
        ),
    ]
