# Generated by Django 4.2.4 on 2023-08-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userinfo_jobfield_userinfo_jobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='jobField',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='jobTitle',
        ),
    ]
