# Generated by Django 4.2.4 on 2023-08-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('api', '0006_remove_userinfo_jobfield_remove_userinfo_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='jobField',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobfield'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='jobTitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle'),
            preserve_default=False,
        ),
    ]
