# Generated by Django 4.2.4 on 2023-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_compleated',
            field=models.BooleanField(default=False),
        ),
    ]
