# Generated by Django 4.2.4 on 2023-08-28 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('api', '0007_userinfo_jobfield_userinfo_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='jobField',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobfield'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jobTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
