# Generated by Django 4.2.4 on 2023-08-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_skills'),
        ('api', '0009_experience_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='jobField',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobfield'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='jobTitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='languages',
            field=models.ManyToManyField(to='dashboard.languages'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skills',
            field=models.ManyToManyField(to='dashboard.skills'),
        ),
    ]
