# Generated by Django 4.2.4 on 2023-09-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userinfo_city_userinfo_state_userinfo_streetaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
