# Generated by Django 4.2.4 on 2023-09-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userinfo_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
