# Generated by Django 4.2.4 on 2023-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userinfo_jobfield_userinfo_jobtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
                ('DatesAttended', models.DateField()),
                ('Datesended', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='education',
            field=models.ManyToManyField(to='api.education'),
        ),
    ]
