# Generated by Django 4.2.4 on 2023-09-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
