# Generated by Django 4.2.4 on 2023-09-25 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('company_size', models.CharField(max_length=100, null=True)),
                ('company_type', models.CharField(max_length=100, null=True)),
                ('gst', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('streetaddress', models.TextField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zipcode', models.BigIntegerField(null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(choices=[('short-term', 'short-term'), ('long-term', 'long-term')], default='long-term', max_length=20)),
                ('level_of_experience', models.CharField(choices=[('fresher', 'fresher'), ('intermediate', 'intermediate'), ('export', 'export')], default='fresher', max_length=20)),
                ('year_of_experience', models.BigIntegerField(blank=True, null=True)),
                ('education', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Jobtitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle')),
                ('companyinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo')),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobfield')),
                ('skills', models.ManyToManyField(to='dashboard.skills')),
            ],
        ),
    ]
