# Generated by Django 4.2.4 on 2023-09-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.post')),
                ('comanyInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo')),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo')),
            ],
        ),
    ]
