# Generated by Django 4.2.4 on 2023-09-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='constry',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='district',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='streetaddress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='zipcode',
            field=models.BigIntegerField(null=True),
        ),
    ]
