# Generated by Django 4.2.4 on 2023-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyinfo_city_companyinfo_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetaddress', models.TextField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zipcode', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='streetaddress',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.ManyToManyField(to='company.companyaddress'),
        ),
    ]
