# Generated by Django 4.2.4 on 2023-09-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyinfo_constry_companyinfo_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='constry',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='contry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
