# Generated by Django 4.2.4 on 2023-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_applyjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobs',
            name='schedule',
            field=models.DateField(default=None, null=True),
        ),
    ]
