# Generated by Django 4.2.4 on 2023-09-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companyinfo_constry_companyinfo_contry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='district',
            new_name='city',
        ),
    ]
