# Generated by Django 4.2.4 on 2023-09-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_district_companyinfo_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='contry',
            new_name='country',
        ),
    ]
