# Generated by Django 4.2.4 on 2023-09-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('company', '0005_rename_contry_companyinfo_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(choices=[('short-term', 'short-term'), ('long-term', 'long-term')], default='long-term', max_length=20)),
                ('level_of_experience', models.CharField(choices=[('fresher', 'fresher'), ('intermediate', 'intermediate'), ('export', 'export')], default='fresher', max_length=20)),
                ('year_of_experience', models.BigIntegerField(blank=True, null=True)),
                ('education', models.TextField()),
                ('description', models.TextField()),
                ('Jobtitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle')),
                ('companyinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo')),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobfield')),
                ('skills', models.ManyToManyField(to='dashboard.skills')),
            ],
        ),
    ]
