# Generated by Django 4.2.4 on 2023-09-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='companyinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyinfo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='education',
            field=models.TextField(null=True),
        ),
    ]
